// spells_data.js

const CLASS_SPELLS = {
	"Paladin": [
    { category: "Palladin", spells: [
        "Absolución",
        "Acusar",
        "Ahuyentar el mal",
        "Arrepentimiento",
        "Aura de devoción",
        "Bendición de poderío",
        "Bendición de reyes",
        "Choque Sagrado",
        "Cólera Sagrada",
        "Cólera vengativa",
        "Consagración",
        "Corazón del cruzado",
        "Defensor candente",
        "Destello de Luz",
        "Dura palabra",
        "Ejecución pospuesta",
        "Emancipación",
        "Escudo de vengador",
        "Escudo divino",
        "Escudo Sagrado",
        "Escudo del honrado",
        "Exorcismo",
        "Expiación",
        "Favor divino",
        "Furia antigua",
        "Glifo de Cólera vengativa",
        "Golpe de cruzado",
        "Guardián de los antiguos reyes",
        "Imposición de manos",
        "Inquisición",
        "Limpiar",
        "Llama eterna",
        "Luz cegadora",
        "Luz de los antiguos reyes",
        "Luz del alba",
        "Luz divina",
        "Luz Sagrada",
        "Mano de libertad",
        "Mano de Luz",
        "Mano de protección",
        "Mano de pureza",
        "Mano de sacrificio",
        "Mano de salvación",
        "Martillo de cólera",
        "Martillo de Justicia",
        "Martillo de la Luz",
        "Martillo del honrado",
        "Palabra de gloria",
        "Prisma Sagrado",
        "Protección divina",
        "Protector del inocente",
        "Radiancia Sagrada",
        "Redención",
        "Reprimenda",
        "Sello de Justicia",
        "Sello de orden",
        "Sello de Perspicacia",
        "Sello de Rectitud",
        "Sello de Verdad",
        "Sentencia",
        "Sentencia de ejecución",
        "Señal de la Luz",
        "Súplica",
        "Tormenta divina",
        "Velocidad de la Luz",
        "Vengador sagrado",
        "Veredicto del templario"
    ]},
    // Aquí podrías agregar más categorías (e.g., Protección, Sagrado, Reprensión)
],
	"Mago": [
	{ category: "Mage", spells: [
	]}
	],
	
	"Druida": [
	{ category: "Dudu", spells: [
	]}
	],
	
	"Guerrero": [
	{ category: "War", spells: [
	]}
	],

	"DK": [
	{ category: "DK_1", spells: [
	"Abrazo de Sanguino",
	"Absorber plaga",
	"Añublo profano",
	"Arma de runa danzante",
	"Asfixiar",
	"Asolar",
	"Atracción letal",
	"Avance de la Muerte",
	"Brote",
	"Cadenas de hielo",
	"Camino de hielo",
	"Caparazón antimagia",
	"Conversión",
	"Controlar no-muerto",
	"Cuerno de invierno",
	"Ejército de muertos",
	"Entereza ligada al hielo",
	"Escudo óseo",
	"Espiral de la muerte",
	"Estrangular",
	"Exánime nato",
	"Explosión aullante",
	"Frenesí profano",
	"Golpe con runa",
	"Golpe de Escarcha",
	"Golpe de la Plaga",
	"Golpe de peste",
	"Golpe en el corazón",
	"Golpe letal",
	"Golpe necrótico",
	"Golpe purulento",
	"Helada mental",
	"Hervor de sangre",
	"Invierno sin remordimientos",
	"Invocar gárgola",
	"Levantar a aliado",
	"Levantar a muerto",
	"Muerte y descomposición",
	"Orden oscura",
	"Pacto de la Muerte",
	"Pestilencia",
	"Pilar de Escarcha",
	"Portón de la muerte",
	"Potenciar arma de runas",
	"Presencia de escarcha",
	"Presencia de sangre",
	"Presencia profana",
	"Sangre vampírica",
	"Segador de almas",
	"Simulación oscura",
	"Suelo profanado",
	"Succión mortal",
	"Toque helado",
	"Transformación oscura",
	"Transfusión de sangre",
	"Transfusión de runa",
	"Zona antimagia",]}
	],
	
	"Rogue": [
	{ category: "RogueKill", spells: [
	]}
	]

}
